const products = [
  {id:1,name:'Daily Carry Tote',category:'Carry',price:78,tag:'BESTSELLER',image:'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=85',description:'A sturdy, unlined canvas tote with a generous base and vegetable-tanned leather handles. For market runs, studio days, and everything between.'},
  {id:2,name:'Ridge Wool Blanket',category:'Home',price:148,tag:'NEW',image:'https://images.unsplash.com/photo-1600369671236-e74521d4b6ad?auto=format&fit=crop&w=900&q=85',description:'Woven in a small mill from soft recycled wool. A warm, substantial layer for the end of the day or the edge of the world.'},
  {id:3,name:'Field Notes No. 04',category:'Paper',price:18,tag:'STUDIO PICK',image:'https://images.unsplash.com/photo-1531346680769-a1d79b57de5c?auto=format&fit=crop&w=900&q=85',description:'A pocket-sized notebook with 96 pages of smooth, toothy paper. The cover gets better with every place it goes.'},
  {id:4,name:'Stoneware Mug',category:'Kitchen',price:34,tag:'',image:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=85',description:'Hand-thrown in Oregon and finished with a quiet matte glaze. Holds 12 ounces of whatever starts your morning.'},
  {id:5,name:'Utility Cap',category:'Carry',price:42,tag:'NEW',image:'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=85',description:'Six-panel cotton twill with a brass adjuster and a low, comfortable crown. Sun protection without the fuss.'},
  {id:6,name:'Cedar + Smoke Candle',category:'Home',price:36,tag:'',image:'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=900&q=85',description:'A grounding blend of cedarwood, hinoki, and a hint of campfire. Hand-poured in a reusable stone vessel.'}
];
const categories = ['All','Carry','Home','Paper','Kitchen'];
const state = {filter:'All',sort:'Featured',cart:load('fw-cart',[]),user:load('fw-session',null),authMode:'login'};
function load(key,fallback){try{return JSON.parse(localStorage.getItem(key)) ?? fallback}catch{return fallback}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
function money(value){return `$${value.toFixed(2)}`}
function product(id){return products.find(item=>item.id===Number(id))}
function renderFilters(){document.querySelector('#filters').innerHTML=categories.map(item=>`<button class="filter ${state.filter===item?'active':''}" data-filter="${item}">${item}</button>`).join('')}
function renderProducts(){let shown=products.filter(item=>state.filter==='All'||item.category===state.filter);if(state.sort==='Price: Low')shown.sort((a,b)=>a.price-b.price);if(state.sort==='Price: High')shown.sort((a,b)=>b.price-a.price);document.querySelector('#product-grid').innerHTML=shown.map((item,index)=>`<article class="product-card" data-product="${item.id}" style="animation-delay:${index*70}ms"><div class="product-image">${item.tag?`<span class="product-tag">${item.tag}</span>`:''}<img src="${item.image}" alt="${item.name}"></div><div class="product-info"><div><h3 class="product-name">${item.name}</h3><span class="product-category">${item.category}</span></div><span class="product-price">${money(item.price)}</span></div></article>`).join('')}
function cartCount(){return state.cart.reduce((sum,item)=>sum+item.quantity,0)}
function renderCart(){const count=cartCount();document.querySelector('#cart-count').textContent=count;document.querySelector('#drawer-count').textContent=count;const items=document.querySelector('#cart-items');if(!count){items.innerHTML='<div class="empty-state"><strong>Your bag is quiet.</strong>Add something useful to get started.</div>';document.querySelector('#cart-footer').innerHTML='';return}items.innerHTML=state.cart.map(item=>{const p=product(item.id);return `<div class="cart-row"><div class="cart-row-image"><img src="${p.image}" alt="${p.name}"></div><div><h3>${p.name}</h3><p>${money(p.price)}</p><div class="qty"><button data-qty="${p.id}" data-change="-1">−</button><span>${item.quantity}</span><button data-qty="${p.id}" data-change="1">+</button></div></div><span class="cart-price">${money(p.price*item.quantity)}</span></div>`}).join('');const total=state.cart.reduce((sum,item)=>sum+product(item.id).price*item.quantity,0);document.querySelector('#cart-footer').innerHTML=`<div class="subtotal"><span>Subtotal</span><strong>${money(total)}</strong></div><button class="button button-dark" data-action="checkout" style="width:100%;justify-content:space-between">Proceed to checkout <span>↗</span></button>`}
function openPanel(id){document.querySelector('#overlay').hidden=false;document.querySelector(id).hidden=false}
function closePanels(){document.querySelector('#overlay').hidden=true;document.querySelectorAll('.drawer,.modal-shell').forEach(item=>item.hidden=true)}
function addToCart(id){const existing=state.cart.find(item=>item.id===id);if(existing)existing.quantity++;else state.cart.push({id,quantity:1});save('fw-cart',state.cart);renderCart();toast('Added to your bag')}
function showProduct(id){const p=product(id);document.querySelector('#product-detail').innerHTML=`<div class="detail-grid"><div class="detail-image"><img src="${p.image}" alt="${p.name}"></div><div class="detail-content"><p class="eyebrow">${p.category} / Fieldwork object ${String(p.id).padStart(2,'0')}</p><h2>${p.name}</h2><div class="price">${money(p.price)}</div><p class="description">${p.description}</p><button class="button button-dark" data-add="${p.id}" style="width:100%;justify-content:space-between">Add to bag <span>＋</span></button><p class="eyebrow" style="margin-top:28px;margin-bottom:0">Ships in 1–2 business days</p></div></div>`;openPanel('#product-modal')}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function updateAccount(){document.querySelector('#account-label').textContent=state.user?state.user.email.split('@')[0]:'Account'}
function openAuth(){if(state.user){state.user=null;save('fw-session',null);updateAccount();toast('You have been logged out');return}openPanel('#auth-modal')}
function submitAuth(event){event.preventDefault();const email=document.querySelector('#auth-email').value;const password=document.querySelector('#auth-password').value;const users=load('fw-users',[]);if(state.authMode==='register'){if(users.some(user=>user.email===email)){document.querySelector('#auth-message').textContent='An account with this email already exists.';return}users.push({email,password});save('fw-users',users)}else if(!users.some(user=>user.email===email&&user.password===password)){document.querySelector('#auth-message').textContent='Email or password not recognized. Create an account first.';return}state.user={email};save('fw-session',state.user);updateAccount();closePanels();toast(state.authMode==='register'?'Account created. Welcome in.':'Welcome back.')}
document.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action==='close')closePanels();if(action==='cart'){renderCart();openPanel('#cart-drawer')}if(action==='account')openAuth();if(action==='shop')document.querySelector('#shop').scrollIntoView({behavior:'smooth'});if(action==='home')window.scrollTo({top:0,behavior:'smooth'});if(action==='about')document.querySelector('#about').scrollIntoView({behavior:'smooth'});if(action==='orders'){toast(state.user?'Orders are coming soon to your account.':'Log in to view your orders.');if(!state.user)openAuth()}if(action==='search'){const query=prompt('Search the collection');if(query){const found=products.find(item=>item.name.toLowerCase().includes(query.toLowerCase()));if(found)showProduct(found.id);else toast('No matching objects found')}}if(action==='sort'){state.sort=state.sort==='Featured'?'Price: Low':state.sort==='Price: Low'?'Price: High':'Featured';event.target.innerHTML=`Sort: ${state.sort} <span>↓</span>`;renderProducts()}if(event.target.matches('[data-filter]')){state.filter=event.target.dataset.filter;renderFilters();renderProducts()}if(event.target.matches('[data-product]')||event.target.closest('[data-product]'))showProduct(event.target.closest('[data-product]').dataset.product);if(event.target.matches('[data-add]')){addToCart(Number(event.target.dataset.add));closePanels();renderCart()}if(event.target.matches('[data-qty]')){const item=state.cart.find(item=>item.id===Number(event.target.dataset.qty));item.quantity+=Number(event.target.dataset.change);if(item.quantity<1)state.cart=state.cart.filter(entry=>entry!==item);save('fw-cart',state.cart);renderCart()}if(action==='checkout'){if(!state.user){closePanels();openAuth();document.querySelector('#auth-message').textContent='Log in to complete your order.'}else{const orders=load('fw-orders',[]);orders.push({id:Date.now(),date:new Date().toLocaleDateString(),items:state.cart});save('fw-orders',orders);state.cart=[];save('fw-cart',state.cart);renderCart();toast('Order placed. Thank you.')}}});
document.querySelector('#overlay').addEventListener('click',closePanels);document.querySelector('#auth-form').addEventListener('submit',submitAuth);document.querySelectorAll('[data-auth]').forEach(tab=>tab.addEventListener('click',()=>{state.authMode=tab.dataset.auth;document.querySelectorAll('[data-auth]').forEach(item=>item.classList.toggle('active',item===tab));document.querySelector('#auth-submit').innerHTML=state.authMode==='login'?'Log in <span>↗</span>':'Create account <span>↗</span>';document.querySelector('#auth-message').textContent=''}));renderFilters();renderProducts();renderCart();updateAccount();